### ISSUE TITLE
Your readme contains a mallard duck emoji, not a loon

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/loon#2]
![Screen Shot 2019-03-22 at 11 46 22 AM](https://user-images.githubusercontent.com/5498428/54835278-2d48da80-4c98-11e9-8678-2e320ff2ab1a.png)

References:
https://en.wikipedia.org/wiki/Mallard
https://en.wikipedia.org/wiki/Common_loon

**Comment by timarney** [comment]
Assigned to @smcmurtry to "Procure loon emoji".

**Comment by maxneuvians** [comment]
Full intent
